//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añaterve
        ///Añes
        ///Aadil
        ///Aali
        ///Aaliyah
        ///Aaltje
        ///Aamar
        ///Aamer
        ///Aamir
        ///Aaron
        ///Aase
        ///Aatika
        ///Aaya
        ///Aba
        ///Ababacar
        ///Abad
        ///Abarca
        ///Abarne
        ///Abass
        ///Abasse
        ///Abba
        ///Abbas
        ///Abbass
        ///Abbes
        ///Abbey
        ///Abbie
        ///Abby
        ///Abdala
        ///Abdalah
        ///Abdalahe
        ///Abdalahi
        ///Abdalla
        ///Abdallah
        ///Abdallahi
        ///Abdel
        ///Abdela
        ///Abdelaali
        ///Abdelaati
        ///Abdelaaziz
        ///Abdeladim
        ///Abdelah
        ///Abdelakrim
        ///Abdelali
        ///Abdelasis
        ///Abdelati
        ///Abdelatif
        ///Abdelazis
        ///Abdelaziz
        ///Abdelazize
        ///Abdelbaki
        ///Abdelbari
        ///Abdelbasset
        ///Abdeldjalil
        ///Abdelelah
        ///Abdelfatah
        ///Abdelfattah
        ///Abdelfetah
        ///Abdelfettah
        ///Abdelghafour
        ///Abdelghani
        ///Abdelhabib
        ///Abdelhad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ñeco
        ///Ñiguez
        ///Açaola
        ///Añaños
        ///Añale
        ///Añazco
        ///Añel
        ///Añez
        ///Añezcar
        ///Añibarro
        ///Añino
        ///Año
        ///Añon
        ///Añorbe
        ///Añorga
        ///Añover
        ///Aaguirre
        ///Aali
        ///Aalsburg
        ///Aalst
        ///Aarab
        ///Aarents
        ///Aarle
        ///Aarns
        ///Aaron
        ///Aaronin
        ///Aaronsen
        ///Aaronson
        ///Aaronstein
        ///Aart
        ///Aarts
        ///Aartz
        ///Aba
        ///Ababei
        ///Ababko
        ///Ababou
        ///Abad
        ///Abadal
        ///Abade
        ///Abades
        ///Abadesso
        ///Abadia
        ///Abadiano
        ///Abadias
        ///Abadie
        ///Abadin
        ///Abadito
        ///Abaev
        ///Abaga
        ///Abagyan
        ///Abaidulin
        ///Abaidullin
        ///Abaigar
        ///Abaimoff
        ///Abaimov
        ///Abaitua
        ///Abaiz
        ///Abajas
        ///Abajo
        ///Abakeliya
        ///Abakovsky
        ///Abakshin
        ///Abakum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surnames {
            get {
                return ResourceManager.GetString("surnames", resourceCulture);
            }
        }
    }
}
